config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homepage#show'

  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
      @items = Item.all.reverse
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, :notice => 'Item added!'
    else
      render action: :new
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path, :notice => 'Item has been successfully deleted!'
  end

  private

  def item_params
    params.require(:item).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<h2>Item ToDo</h2>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.description %></td>
          <td><%= button_to 'Delete', item_path(item), method: 'delete' %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/homepage/show.html.erb
<h1>Let's get it done!</h1>

<%= link_to 'Add Item', new_item_path %>

<table>
  <thead>
    <tr>
      <th>ToDo</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= link_to ('<i class="fa fa-trash-o"><p class="delete">delete</p></i>').html_safe, item_path(item), method: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%= form_for @item do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <% if @item.new_record? %>
    <%= form.submit 'Add it!' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src = 'https://use.fontawesome.com/44f5f8d11c.js'></script>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Open+Sans+Condensed:300" rel="stylesheet">
  </head>

  <body>

    <% if flash[:notice].present? %>
      <p class='notice'><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>